-- 相机/EXIF 信息
ALTER TABLE photos ADD COLUMN focal_length VARCHAR(64) NULL;
ALTER TABLE photos ADD COLUMN aperture VARCHAR(32) NULL;
ALTER TABLE photos ADD COLUMN shutter_speed VARCHAR(32) NULL;
ALTER TABLE photos ADD COLUMN iso VARCHAR(32) NULL;
ALTER TABLE photos ADD COLUMN camera VARCHAR(255) NULL;
ALTER TABLE photos ADD COLUMN lens VARCHAR(255) NULL;
